env:
  global:
    - NDK_VERSION=r10e
    - FUSE_VERSION=0.35.0.10867
    - UNOPROJ=hockeyapp_example
    - NAME=hockeyapp_example

language: 
  - fuse
  - objective-c
  - android
  - node_js
os:
  - osx
sudo: required

cache:
  directories:
#    - /Applications/Fuse.app
#    - /usr/local/share/uno
#    - $HOME/.fuse
    - $HOME/Library/Android
#    - $HOME/fuse


before_install:
  - ./.travis/install-ndk.sh
  - ./.travis/install-fuse.sh
  - expect ./.travis/install-fuseandroid.expect
  - ./.travis/install-fusepm.sh

before_script:
    - fusepm install --unoproj ${UNOPROJ}.unoproj
# http://stackoverflow.com/questions/27671854/travis-ci-fails-to-build-with-a-code-signing-error
#     - ./.travis/add-key.sh

script:
  - ./.travis/test_uno.sh
  - ./.travis/test_ios.sh
  - ./.travis/test_android.sh

# before_cache:
#   - mkdir $HOME/fuse
#   - mv "/Users/travis/Library/Application Support/Fusetools" $HOME/fuse/appsupport
